// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBETr5v_CxdqnnY6dRyTIZr8roWTo_giy0',
    appId: '1:506669116292:web:79e1a1d884e74e96720bd1',
    messagingSenderId: '506669116292',
    projectId: 'todo-app-ea02c',
    authDomain: 'todo-app-ea02c.firebaseapp.com',
    storageBucket: 'todo-app-ea02c.appspot.com',
    measurementId: 'G-TDCWCBSZNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBOb9bZdZbjBXmnvuUEqAhKCmaGCYk6X4',
    appId: '1:506669116292:android:8546c664eae7aa14720bd1',
    messagingSenderId: '506669116292',
    projectId: 'todo-app-ea02c',
    storageBucket: 'todo-app-ea02c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9ZIGoDxVfWN98cHzAWn09CPwAGQIlJ9k',
    appId: '1:506669116292:ios:e45ff94cb84e1de8720bd1',
    messagingSenderId: '506669116292',
    projectId: 'todo-app-ea02c',
    storageBucket: 'todo-app-ea02c.appspot.com',
    iosBundleId: 'com.example.newTasksApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9ZIGoDxVfWN98cHzAWn09CPwAGQIlJ9k',
    appId: '1:506669116292:ios:ac7258b7cd4883ba720bd1',
    messagingSenderId: '506669116292',
    projectId: 'todo-app-ea02c',
    storageBucket: 'todo-app-ea02c.appspot.com',
    iosBundleId: 'com.example.newTasksApp.RunnerTests',
  );
}
